basePath: /
definitions:
  errs.APIError:
    properties:
      message: {}
      statusCode:
        type: integer
    type: object
  models.BulkPresignedURLRequest:
    properties:
      files:
        items:
          $ref: '#/definitions/models.PresignedURLRequest'
        minItems: 1
        type: array
    required:
    - files
    type: object
  models.BulkPresignedURLResponse:
    properties:
      files:
        items:
          $ref: '#/definitions/models.FilePresignedURLResponse'
        type: array
    type: object
  models.CreateUserRequest:
    properties:
      name:
        minLength: 1
        type: string
      username:
        type: string
    required:
    - name
    - username
    type: object
  models.FilePresignedURLResponse:
    properties:
      fileKey:
        type: string
      urls:
        items:
          $ref: '#/definitions/models.PresignedURLResponse'
        type: array
    type: object
  models.ImageSize:
    enum:
    - small
    - medium
    - large
    type: string
    x-enum-varnames:
    - ImageSizeSmall
    - ImageSizeMedium
    - ImageSizeLarge
  models.PresignedURLRequest:
    properties:
      fileKey:
        minLength: 1
        type: string
      sizes:
        items:
          $ref: '#/definitions/models.ImageSize'
        minItems: 1
        type: array
    required:
    - fileKey
    - sizes
    type: object
  models.PresignedURLResponse:
    properties:
      size:
        $ref: '#/definitions/models.ImageSize'
      url:
        type: string
    type: object
  models.S3HealthCheckResponse:
    properties:
      bucketName:
        type: string
      region:
        type: string
      status:
        type: string
    type: object
  models.UpdateUserRequest:
    properties:
      name:
        minLength: 1
        type: string
      username:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Bringing group travel plans to life
  title: Toggo API
  version: "1.0"
paths:
  /api/v1/files/health:
    get:
      description: Verifies connectivity to the configured S3 bucket
      operationId: checkS3Health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.S3HealthCheckResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.APIError'
      summary: Check S3 connection
      tags:
      - files
  /api/v1/files/presigned-urls:
    post:
      consumes:
      - application/json
      description: Generates presigned URLs for multiple files with specified sizes
      operationId: getBulkPresignedURLs
      parameters:
      - description: Bulk presigned URL request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BulkPresignedURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BulkPresignedURLResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.APIError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.APIError'
      summary: Get bulk presigned URLs
      tags:
      - files
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Creates a new user with the provided payload
      operationId: createUser
      parameters:
      - description: Create user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.APIError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.APIError'
      summary: Create a new user
      tags:
      - users
  /api/v1/users/{userID}:
    delete:
      description: Deletes a user by ID
      operationId: deleteUser
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errs.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.APIError'
      summary: Delete a user
      tags:
      - users
    get:
      description: Retrieves a user by ID
      operationId: getUser
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errs.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.APIError'
      summary: Get a user
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Updates an existing user by ID
      operationId: updateUser
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Update user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errs.APIError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.APIError'
      summary: Update a user
      tags:
      - users
  /healthcheck:
    get:
      description: Returns OK if the server is running and database is healthy
      operationId: healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Healthcheck endpoint
      tags:
      - example
swagger: "2.0"
